Repository VKSRC/Github-Monitor, pull requests merged in 2018-12, with the labels that each got.

#4 fixed task in processor cannot reload after updated task
  server/github_monitor/apps/monitor/processors.py
Labels: bug

#6 fixed task name didn't allow unicode
  server/github_monitor/apps/monitor/serializers/task_serializers.py
Labels: bug

#10 fixed email ssl/tls settings & update readme
  .env.docker
  .env.sample
  README.md
  server/github_monitor/settings.py
Labels: bug, document

#15 fixed url error, fix #14
  client/dist/11.async.js
  client/dist/13.async.js
  client/dist/16.async.js
  client/dist/5.async.js
  client/dist/6.async.js
  client/dist/8.async.js
  client/dist/9.async.js
  client/dist/color.less
  client/dist/umi.css
  client/dist/umi.js
  client/dist/vendors.async.js
  client/dist/vendors.chunk.css
  client/src/pages/Tasks/TaskLists.js
Labels: bug

#21 :memo: add CHANGELOG.md
  CHANGELOG.md
Labels: document
